#--------------------------------------------------------------------------------- General
general:
  name: forex_download

#--------------------------------------------------------------------------------- Database
database:
  main:
    host: 127.0.0.1
    port: 5432
    user: forex
    pass: "&WnA8v!(THG%)czK"
    name: forex

#--------------------------------------------------------------------------------- Api
api:
  title: forex_api
  description: This is my custom API schema description
  version: '1.0.0'
  openapi_url: /schema
  docs_url: /doc1
  redoc_url: /doc2
  key: "e21d6dfd-85cf-4886-a512-8c6e432bf9c9"
  host: 127.0.0.1
  port: 7001
  workers: 3

#--------------------------------------------------------------------------------- Log
log:
  #---------------------------------Database
  database:
    host: 127.0.0.1
    port: 5432
    user: forex
    pass: "&WnA8v!(THG%)czK"
    name: log
  #---------------------------------General
  general:
    table: forex
    file: log.txt
  #---------------------------------Error
  error:
    verbose: True
    file: False
    database: False
  #---------------------------------Report
  report:
    verbose: True
    file: False
    database: False
  #---------------------------------Notification
  notification:
    verbose: True
    file: False
    database: False

#--------------------------------------------------------------------------------- FXCM
forex_connect:
  default: acc-history1
  acc-history1:
    server    : 'Demo'
    username  : '52030299'
    password  : '2idfycj'
    url       : 'http://www.fxcorporate.com/Hosts.jsp'
    key       : ''
  acc-history2:
    server    : 'Demo'
    username  : '52032860'
    password  : 'aq8iwnf'
    url       : 'http://www.fxcorporate.com/Hosts.jsp'
    key       : ''
  acc-live:
    server    : 'Demo'
    username  : '52035533'
    password  : 'iaee0at'
    url       : 'http://www.fxcorporate.com/Hosts.jsp'
    key       : ''
  acc-trade:
    server    : 'Demo'
    username  : '52035534'
    password  : 'fjf0tzq'
    url       : 'http://www.fxcorporate.com/Hosts.jsp'
    key       : ''

#--------------------------------------------------------------------------------- Download
download:
  instrument: XAU/USD
  timeframe: t1
  mode: up
  count: 1000
  repeat: 1
  delay: 0
  save: True
  bulk: True
  clear: False
  dedicate: False
  datefrom: '2000-01-01 00:00:00'
  dateto: '2030-01-01 00:00:00'
  
#--------------------------------------------------------------------------------- instrument
instrument:
  table: instrument
  useDefaultSymbols: True
  defaultSymbols: [
      "EUR/USD", "EUR/GBP", "EUR/CHF", "EUR/JPY", "EUR/AUD", "EUR/CAD", "EUR/NZD",
      "GBP/USD", "GBP/JPY", "GBP/CHF", "GBP/NZD", "GBP/AUD", "GBP/CAD",
      "AUD/USD", "AUD/CAD", "AUD/JPY", "AUD/NZD", "AUD/CHF",
      "NZD/USD", "NZD/JPY", "NZD/CHF", "NZD/CAD",
      "USD/JPY", "USD/CHF", "USD/CAD",
      "CAD/JPY", "CAD/CHF",
      "CHF/JPY",
      "USOil", "UKOil", "XAU/USD", "XAG/USD"]

#--------------------------------------------------------------------------------- timeframe
timeframe: ["W1", "D1", "H8", "H6", "H4", "H3", "H2", "H1", "m30", "m15", "m5", "m1", "t1"]